name: Deploy Vue Frontend

# Memicu hanya saat push ke branch 'main'
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_SERVER }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}

        # Perintah yang akan dijalankan di VPS
        script: |
          # Masuk ke direktori Vue
          cd /var/www/leksigo-client 

          # Tarik perubahan terbaru
          echo "Pulling latest code..."
          git pull origin main

          # Install dependencies & build
          echo "Building Vue app..."
          npm install
          npm run build

          echo "Deploy Frontend Selesai!"